version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: /module5/circleci/calculator  # Update this path to match your project structure
    steps:
      - checkout
      - run: mvn clean
      - run: mvn test 
      - run: mvn install    


  lint:
    docker:
      - image: python:3.8
    working_directory: /module5/circleci  # Update this path to match your project structure
    steps:
      - checkout
      - run:
          name: Lint
          command: |
            pip install flake8
            flake8

  test:
    docker:
      - image: python:3.8
    working_directory: /module5/circleci/calculator  # Update this path to match your project structure
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: |
             

  deploy:
    docker:
      - image: python:3.8
    working_directory: /module5/circleci  # Update this path to match your project structure
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            mkdir -p DEPLOY-$(date +"%Y%m%d")
            cp -r * DEPLOY-$(date +"%Y%m%d")/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - lint:
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - test:
          requires:
            - lint
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - main

