version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/circleci-demo  # Update this path to match your project structure
    steps:
      - checkout 
      - run: mvn clean install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8    


  lint:
    docker:
      - image: python:3.8
    working_directory: /module5/circleci  # Update this path to match your project structure
    steps:
      - checkout
      - run:
          name: Lint
          command: |
            pip install flake8
            flake8

  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/circleci-demo  # Update this path to match your project structure
    steps:
      - checkout
      - run: mvn test -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
        
          
             

  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/circleci-demo  # Update this path to match your project structure
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            mkdir -p ~/circleci-demo-extension/DEPLOY-$(date +"%Y%m%d")
            cp -r *  ~/circleci-demo-extension/DEPLOY-$(date +"%Y%m%d")/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - lint:
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - test:
          requires:
            - lint
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - main

