version: 2.1

jobs:
  build:
    docker:
      - image: circleci/test.js # Specify your Docker image
    working_directory: /module5
    steps:
      - checkout
      - run:
          name: Build
          command: |
            # Add your build commands here
            echo "Building RS Software"

  deploy:
    docker:
      - image: circleci/test.js # Specify your Docker image
    working_directory: /module5
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            # Add your deployment commands here
            echo "Deploying RS Software"
            mkdir DEPLOY-$(date +"%Y%m%d")

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main

